.TH NETSELECT-APT 1 "March 6, 2008" "DEBIAN" \" -*- nroff -*-
.\" Please adjust this date whenever revising the manpage.

.SH NAME
netselect-apt \- create sources.list for the fastest Debian mirrors

.SH SYNOPSIS
.B netselect-apt
.RI [ OPTIONS ]
.\" copied verbatim from netselect-apt
.RI [ \|stable | testing | unstable | experimental | \fIrelease_codename\fR | sid ]

.SH DESCRIPTION

.B netselect-apt
automatically creates a \fIsources.list\fR file for using with
.BR apt
for the specified distribution by downloading the list of Debian
mirrors using
.B wget
choosing the fastest servers using
.BR netselect ,
and testing the valid servers using
.BR curl 
(if available). The output file is written to
.IR OUTFILE .

The list of fastest servers is determined by checking through 
.BR netselect ,
which servers responder faster to ICMP queries. In order to determine if the
servers are valid a connectiong using the specificied protocol (HTTP or FTP)
is done using
.BR curl .

If 
.BR netselect
is not installed setuid, then 
.BR netselect-apt
needs to run as an administrator user (i.e. root). This is only required
because the network probes done by 
.BR netselect
requires these permissions. No changes are done to the system.

If
.BI "\-i" " INFILE"
is passed
.B netselect-apt
uses that rather than downloading another copy to a temporary file. The file
will be downloaded from http://www.debian.org/mirror/mirrors_full

.SH OPTIONS
.TP
.IR stable | testing | unstable | experimental | \fIrelease_codename\fR | sid
Specify which distribution of Debian to use.  By default
.I stable
is used.
.TP
.BI "\-a, \-\-arch" " ARCH"
Use mirrors containing \fIARCH\fR. By default the architecture of the current
machine is used as reported by \fBdpkg\fR
.TP
.B \-s, \-\-sources
While generating
.I OUTFILE
include also deb-src lines to use with ``apt-get source'' to obtain
Debian source packages.
.TP
.BI "\-i, \-\-infile" " INFILE"
Use
.I INFILE
instead of downloading the mirror list to a temporary file. The file must be in
the same format as mirrors_full.
.TP
.BI "\-o, \-\-outfile" " OUTFILE"
Use
.I OUTFILE
instead of sources.list.
.TP
.B \-n, \-\-nonfree
Include also non-free section while generating
.IR OUTFILE .
.TP
.B \-f, \-\-ftp
Use FTP mirrors instead of HTTP and generate
.I OUTFILE
accordingly.
.TP
.BI "\-O" " OPTIONS"
The 
.I OPTIONS
provided are added, verbatim, to 
.I netselect 
when it is run. Here you can provide a (quoted) list of options for netselect.
.TP
.BI "\-t, \-\-tests" " hosts"
Make a short list with the number of hosts provided and use that list to
test for mirror validity.  By default
.I 10
hosts are tested.
.TP
.BI "\-c, \-\-country" " COUNTRY"
Only test the sites found under the country
.I COUNTRY
(the value can either be an ISO-3166 value or the full name of the language, in English).
When this value is set the mirror list or the
.I INFILE
will be filtered and only the sites that are listed under the given country will be
tested. Note that restricting the search might not give the best results, as
the "fastest" mirror might not even be in the same country as the system the 
program is running in.

.SH ENVIRONMENT
.TP
.B WANT_SOURCES
setting this to 1 is equivalent to --sources
.TP
.B WANT_NONFREE
setting this to 1 is equivalent to --nonfree

.SH LIMITATIONS
.BR netselect-apt
is unable to work with restricted environments in which network filtering is
implemented as it relies on 
.BR netselect
being able to find a suitable mirror. To do this, the system where the script is run
needs to have network visibility of the mirrors, as it will probe them using ICMP probes.

.BR netselect-apt
is also unable to work in environments where HTTP or FTP network connections have to be
done through a proxy host, as it relies on being able to test the validity of the
remote mirrors doing direct network connections to them.

.BR netselect-apt
will not check if the mirror it suggests as the "fastest" mirror is either valid or
up-to-date. It is recommended that users that use this tool also validate that the
mirrors suggested are official mirrors and are also current.


.SH SEE ALSO
.BR netselect (1),
.BR wget (1),
.BR curl (1),
.BR apt (8),
.IR sources.list (5).

For Debian GNU/Linux it is recommended that users review the official mirror
list at http://www.debian.org/mirror/official as well as the mirror checker
tool at http://mirror.debian.org/status.html (which provides information on the
up-to-dateness status of mirrors)

.SH AUTHOR
Avery Pennarun <apenwarr@gmail.com>

This manual page and program have been also enhanced by
Filippo Giunchedi <filippo@esaurito.net> and Javier Fernandez-Sanguino <jfs@debian.org>

